// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherApp.Data;

#nullable disable

namespace WeatherApp.Migrations
{
    [DbContext(typeof(CityWeatherDbContext))]
    [Migration("20230603194150_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherApp.Models.CityWeather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Temp_C")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Temp_F")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Warsaw",
                            Country = "Poland",
                            Info = "Clear",
                            LastUpdate = new DateTime(2023, 6, 3, 21, 41, 49, 923, DateTimeKind.Local).AddTicks(6260),
                            Temp_C = 16.00m,
                            Temp_F = 60.80m
                        },
                        new
                        {
                            Id = 2,
                            CityName = "London",
                            Country = "United Kingdom",
                            Info = "Sunny",
                            LastUpdate = new DateTime(2023, 6, 3, 21, 41, 49, 923, DateTimeKind.Local).AddTicks(6365),
                            Temp_C = 19.0m,
                            Temp_F = 66.20m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
